name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Android APK (debug) with Gradle
      run: ./gradlew build
    - name: Build Android app bundle (debug) with Gradle
      run: ./gradlew bundle
    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Debug APK file
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload Debug Android app bundle artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Debug Android app bundle file
        path: app/build/outputs/bundle/debug/app-debug.aab
