name: Build Android App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle (.apk)
      run: ./gradlew build
    - name: Build Android App Bundle (.aab)
      run: ./gradlew bundle
    - name: Upload Android Package artifact (.apk)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Debug .apk artifact
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload Android App Bundle Artifact (.aab)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Debug .aab artifact
        path: app/build/outputs/bundle/debug/app-debug.aab
